fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    ini_file: git@github.com:puppetlabs/puppetlabs-inifile.git
    htpasswd: git@github.com:leinaddm/puppet-htpasswd.git
    apache: git@github.com:puppetlabs/puppetlabs-apache.git
    sudo: git@github.com:saz/puppet-sudo.git
  symlinks:
    apache: "#{source_dir}"
